# Generated by Django 2.0.13 on 2019-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0002_auto_20190412_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='columncheck',
            name='null_values',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columncheck',
            name='special_characters',
            field=models.BooleanField(default=True),
        ),
    ]
