# Generated by Django 2.0.13 on 2019-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0004_auto_20190412_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='columncheck',
            name='max',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='columncheck',
            name='min',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
