# Generated by Django 2.0.13 on 2019-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0005_auto_20190412_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncheck',
            name='max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='columncheck',
            name='min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
