# Generated by Django 2.0.13 on 2019-04-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0011_auto_20190412_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='columncheck',
            name='max_allowed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='columncheck',
            name='min_allowed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
