# Generated by Django 2.0.13 on 2019-04-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0012_auto_20190413_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='columncheck',
            name='max_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='columncheck',
            name='min_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
