# Generated by Django 2.0.13 on 2019-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0013_auto_20190415_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='columncheck',
            name='max_allowed_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='columncheck',
            name='min_allowed_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
