# Generated by Django 2.0.13 on 2019-04-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_csv_app', '0014_auto_20190415_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncheck',
            name='max_allowed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='columncheck',
            name='max_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='columncheck',
            name='min_allowed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='columncheck',
            name='min_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
